#!/usr/bin/perl
# Emit a kModels entry for src/tv_library.cpp from a Flipper-IRDB ".ir" file.
#
#   perl tools/flipper-table.pl <file.ir> <id> <brand> <model-label>
#
# Uses tools/flipper-import.pl for the encoding, so there is exactly one
# implementation of every protocol layout. Buttons this firmware has no slot
# for are dropped; slots the remote does not have stay TV_NO_CODE.
use strict;
use warnings;
use File::Basename;

my ($file, $id, $brand, $label) = @ARGV;
die "usage: flipper-table.pl <file.ir> <id> <brand> <model-label>\n"
  unless defined $label;

# The firmware's button order. Each entry lists the Flipper names that mean it,
# most preferred first -- the database is not consistent about naming.
my @SLOTS = (
  [ 'TVB_POWER',     qw(Power POWER Power_on) ],
  [ 'TVB_VOL_UP',    qw(Vol_up VOL_UP Volume_up Vol_Up) ],
  [ 'TVB_VOL_DOWN',  qw(Vol_dn Vol_down VOL_DOWN Volume_down Vol_Dn) ],
  [ 'TVB_CH_UP',     qw(Ch_next Ch_up CH_UP Channel_up Ch_Next) ],
  [ 'TVB_CH_DOWN',   qw(Ch_prev Ch_dn Ch_down CH_DOWN Channel_down Ch_Prev) ],
  [ 'TVB_MUTE',      qw(Mute MUTE) ],
  [ 'TVB_INPUT',     qw(Source Input INPUT Av) ],
  [ 'TVB_HOME',      qw(Home HOME Smart) ],
  [ 'TVB_BACK',      qw(Back Return Exit BACK) ],
  [ 'TVB_OK',        qw(Ok OK Enter Select) ],
  [ 'TVB_UP',        qw(Up UP) ],
  [ 'TVB_DOWN',      qw(Down DOWN) ],
  [ 'TVB_LEFT',      qw(Left LEFT) ],
  [ 'TVB_RIGHT',     qw(Right RIGHT) ],
  [ 'TVB_MENU',      qw(Menu Settings MENU) ],
  [ 'TVB_NETFLIX',   qw(Netflix NETFLIX) ],
  [ 'TVB_POWER_ON',  qw(Power_on PowerOn) ],
  [ 'TVB_POWER_OFF', qw(Power_off PowerOff) ],
);

my $dir = dirname(__FILE__);
my @lines = `perl "$dir/flipper-import.pl" "$file" 2>/dev/null`;
die "no convertible signals in $file\n" unless @lines;

my (%code, %proto, %bits, %count);
for (@lines) {
  next unless /^(\S+)\s+(\S+)\s+(\d+) bits\s+value=0x([0-9A-F]+)/;
  my ($n, $p, $b, $v) = ($1, $2, $3, $4);
  next if exists $code{$n};          # first occurrence wins
  $code{$n} = hex $v; $proto{$n} = $p; $bits{$n} = $b;
  $count{"$p/$b"}++;
}

# One remote, one protocol: take the dominant one and ignore stragglers, which
# are almost always a stray signal captured from a different device.
my ($dominant) = sort { $count{$b} <=> $count{$a} } keys %count;
my ($dp, $db) = split m{/}, $dominant;

my %PROTO_VAR = (
  'NIKAI/24'   => 'kNikai',
  'NEC/32'     => 'kNec',
  'SAMSUNG/32' => 'kSamsung32',
  'SONY/12'    => 'kSony12',
  'SONY/15'    => 'kSony15',
  'SONY/20'    => 'kSony20',
);
my $var = $PROTO_VAR{$dominant}
  or die "no TvProtocol defined for $dominant\n";

printf "/// %s -- %s, generated by tools/flipper-table.pl from Flipper-IRDB.\n",
       $brand, $dp;
printf "static const uint32_t k%sCodes[TVB__COUNT] = {\n", ucfirst lc $brand;

my $known = 0;
my (%seen, @dups);
for my $slot (@SLOTS) {
  my ($name, @aliases) = @$slot;
  my ($hit) = grep { exists $code{$_} && "$proto{$_}/$bits{$_}" eq $dominant }
              @aliases;
  if (defined $hit) {
    # Two buttons sharing a code is nearly always an upstream mistake -- the
    # database does contain them (Samsung.ir has Ch_next and Ch_prev both on
    # command 0x10). Emitting it anyway would give a channel-down button that
    # changes channel the wrong way, which is worse than an absent one, so the
    # collision is dropped and reported.
    if (my $prev = $seen{$code{$hit}}) {
      push @dups, "$name shares a code with $prev";
      printf "  /* %-13s */ TV_NO_CODE,   // DROPPED: same code as %s\n",
             $name, $prev;
      next;
    }
    $seen{$code{$hit}} = $name;
    printf "  /* %-13s */ 0x%08X,   // %s\n", $name, $code{$hit}, $hit;
    $known++;
  } else {
    printf "  /* %-13s */ TV_NO_CODE,\n", $name;
  }
}
print "};\n\n";
printf STDERR "  !! %s\n", $_ for @dups;
printf "  { \"%s\", \"%s\", \"%s\", &%s, k%sCodes, \"\" },\n",
       $id, $brand, $label, $var, ucfirst lc $brand;
printf STDERR "%-12s %-11s %2d/18 buttons\n", $brand, $dominant, $known;
